version: '3'

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    command: python ./manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db
volumes:
  db-data:
