version: '3'

services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: username
        POSTGRES_DB: dbname
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  app:
    build: .
    command: bash -c "django-admin startproject django_app; django_app/manage.py runserver"
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - db
volumes:
  db-data:
